# Word-based model
word:
  architecture:
    embedding_dim: 128
    gru_dim: 128
    dense_dim: 128
    dropout: 0.5
    
  training:
    batch_size: 512
    learning_rate: 0.001

# Word-based model - SEQUENCE
word_sequence:
  architecture:
    embedding_dim: 32
    gru_dim: 256
    dense_dim: 128
    dropout: 0.25 

  training:
    batch_size: 128
    learning_rate: 0.01

# Character-based model
char:
  architecture:
    embedding_dim: 128
    gru_dim: 128
    dense_dim: 128
    dropout: 0.5
    
  training:
    batch_size: 512
    learning_rate: 0.001